_BASE_: "../Base-RCNN-FPN.yaml"
CATS_UES_JSON: "xxx/xxx/xxx/dataset/annotations/base_train.json"
MODEL:
  WEIGHTS: "xxx/xxx/xxx/hifsod/checkpoints/fuse_flat_hie/base_training/model_0009999.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "Hierarchical_ROIHeads_Independent_Reg"
    OUTPUT_LAYER: "FastRCNNOutputLayers"
    NUM_CLASSES: 1145
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
DATASETS:
  TRAIN: ('bird_base_train',)
  TEST: ('bird_test_base',)
BALANCE_TRAIN_TREE:
  ENABLE: True
  MAX_SAMPLE_RATE: 5
SOLVER:
  IMS_PER_BATCH: 2
  STEPS: (100000, 180000)
  MAX_ITER: 220000
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "checkpoints/fuse_flat_hie/base_training"

