_BASE_: "../Base-RCNN-FPN.yaml"
CATS_UES_JSON: "xxx/xxx/xxx//datasplit/8k.json"
MODEL:
  WEIGHTS: "checkpoints/simple_root1/model_files/model_combine_2shot.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "Hierarchical_ROIHeads_Weight"
    OUTPUT_LAYER: "FastRCNNOutputLayers"
    NUM_CLASSES: 1432
    FREEZE_FEAT: False
    BATCH_SIZE_PER_IMAGE: 256
  BACKBONE:
    FREEZE: False
    FREEZE_AT: 5
  PROPOSAL_GENERATOR:
    FREEZE: False
  RPN:
    POST_NMS_TOPK_TRAIN: 2000
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
  ROOT_WEIGHT: 1.0
DATASETS:
  TRAIN: ('coco_trainval_all_2shot_seed1',)
  TEST: ('bird_test_all',)
BALANCE_TRAIN_TREE:
  ENABLE: True
  MAX_SAMPLE_RATE: 10
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  GAMMA: 0.3
  STEPS: (70000,)
  MAX_ITER: 120000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 200
TEST:
  AUG:
    ENABLED: True
  EVAL_PERIOD: 5000

OUTPUT_DIR: "checkpoints/simple_root1/ft_2shot_all"
