_BASE_: "../Base-RCNN-FPN.yaml"
CATS_UES_JSON: "xxx/xxx/xxx/dataset/annotations/base_train.json"
MODEL:
  WEIGHTS: "xxx/xxx/xxx/hifsod/checkpoints/MSRA_RES101/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NAME: "Hierarchical_ROIHeads_Independent_Reg_Head"
    OUTPUT_LAYER: "FastRCNNOutputLayers"
    NUM_CLASSES: 1145
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
DATASETS:
  TRAIN: ('bird_base_train',)
  TEST: ('bird_test_base',)
BALANCE_TRAIN_TREE:
  ENABLE: True
  MAX_SAMPLE_RATE: 5
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (100000, 180000)
  MAX_ITER: 220000
TEST:
  EVAL_PERIOD: 10000
OUTPUT_DIR: "checkpoints/fuse_flat_hie_ind_head/base_training"
