_BASE_: "../Base-RCNN-FPN.yaml"
CATS_UES_JSON: "xxx/xxx/hibird/new_annos/base_train.json"
MODEL:
  WEIGHTS: "checkpoints/model_files/model_pretrain_reset.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
  ROI_HEADS:
    NAME: "Hierarchical_ROIHeads_Weight"
    OUTPUT_LAYER: "FastRCNNOutputLayers_WithFC"
    NUM_CLASSES: 1145
    FREEZE_FEAT: False
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
  ROOT_WEIGHT: 1.0
DATASETS:
  TRAIN: ('bird_base_train',)
  TEST: ('bird_test_base',)
BALANCE_TRAIN_TREE:
  ENABLE: True
  MAX_SAMPLE_RATE: 5
SOLVER:
  IMS_PER_BATCH: 18
  STEPS: (60000, 80000)
  MAX_ITER: 90000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "checkpoints/base_hierarchical"
