_BASE_: "../../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "xxx/xxx/HIFSOD/checkpoints/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 1145
DATASETS:
  TRAIN: ('bird_base_train',)
  TEST: ('bird_test_base',)
SOLVER:
  IMS_PER_BATCH: 18
  STEPS: (70000, 80000)
  MAX_ITER: 90000
OUTPUT_DIR: "checkpoints/base_pretraining"
